[2024-07-07T23:54:22.608+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_workflow_SCASTRO.load_data manual__2024-07-07T23:54:17.821925+00:00 [queued]>
[2024-07-07T23:54:22.620+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_workflow_SCASTRO.load_data manual__2024-07-07T23:54:17.821925+00:00 [queued]>
[2024-07-07T23:54:22.621+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-07T23:54:22.639+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): load_data> on 2024-07-07 23:54:17.821925+00:00
[2024-07-07T23:54:22.645+0000] {standard_task_runner.py:60} INFO - Started process 142 to run task
[2024-07-07T23:54:22.649+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_workflow_SCASTRO', 'load_data', 'manual__2024-07-07T23:54:17.821925+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dmc_pipeline.py', '--cfg-path', '/tmp/tmpa_9x1pr9']
[2024-07-07T23:54:22.651+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask load_data
[2024-07-07T23:54:22.712+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_workflow_SCASTRO.load_data manual__2024-07-07T23:54:17.821925+00:00 [running]> on host afd8cf89e8c6
[2024-07-07T23:54:22.812+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_workflow_SCASTRO' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T23:54:17.821925+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-07T23:54:17.821925+00:00'
[2024-07-07T23:54:22.818+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dmc_pipeline.py", line 36, in load_data
    df = pd.read_csv('train.csv')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'
[2024-07-07T23:54:22.832+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_workflow_SCASTRO, task_id=load_data, execution_date=20240707T235417, start_date=20240707T235422, end_date=20240707T235422
[2024-07-07T23:54:22.852+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task load_data ([Errno 2] No such file or directory: 'train.csv'; 142)
[2024-07-07T23:54:22.863+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-07T23:54:22.901+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
